export enum OpeningEntityEnum {
  ZOMBIE = "ZOMBIE",
  // HEALTH_KIT = "HEALTH_KIT",
  PALLET = "PALLET",
  // KNIFE = "WEAPON_KNIFE",
  // HANDGUN = "WEAPON_HANDGUN",
  // ASSAULT_RIFLE = "WEAPON_ASSAULT_RIFLE",
  // RPG = "WEAPON_RPG",
}
